import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "./components/Headers/TopBar";
import Navbar from "./components/Headers/Navbar";
import { Footer } from "./components/Footer";
import { WishListProvider } from '@/app/components/WishList/WishListContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jolly Homes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WishListProvider>
          <TopBar />
          <Navbar />
          {children}
          <Footer />
        </WishListProvider>
      </body>
    </html>
  );
}
